### ISSUE TITLE
Questions about the version of tensorflow?

### ISSUE THREAD

**Issue by wudongming97** [shiyujiao/cross_view_localization_CVFT#2]
Hi.
Could you release your version of tensorflow? I tried 1.3, 1.4, 2.0, and 2.3, but there are always some errors about tensorflow.

**Comment by shiyujiao** [comment]
I cannot remember the exact version of TensorFlow which I used in this code, but It should be 1.10 or 1.12.

**Comment by YujiaoShi** [comment]
> Hi.
> Could you release your version of tensorflow? I tried 1.3, 1.4, 2.0, and 2.3, but there are always some errors about tensorflow.

I cannot remember the exact version of TensorFlow which I used in this code, but It should be 1.10 or 1.12.

**Comment by wudongming97** [comment]
> > Hi.
> > Could you release your version of tensorflow? I tried 1.3, 1.4, 2.0, and 2.3, but there are always some errors about tensorflow.
> 
> I cannot remember the exact version of TensorFlow which I used in this code, but It should be 1.10 or 1.12.

Thanks a lot. It works.
