### ISSUE TITLE
Results error on CVACT dataset

### ISSUE THREAD

**Issue by wudongming97** [shiyujiao/cross_view_localization_CVFT#3]
Sorry, I encounter to a new problem about the accuracy on CVACT dataset. I run the pretrained model that you provide, but the result is different from yours. I list it as following. Could you check your model again?

```
CVFT  done...
top1 : 0.08318325078793336
top5 : 0.2161188653759568
top10 : 0.29828905898244035
top1% : 0.6508329581269698
```

**Comment by YujiaoShi** [comment]
Thanks for your interest. 

We have preprocessed the satellite images and street-view panoramas to fit the input model size. Please refer to "https://github.com/shiyujiao/cross_view_localization_SAFA/blob/master/script/data_preparation.py" for the preparation of street-view panoramas.

But from my experience, if there is little change in the image reading package, (e.g. from scipy to PIL.Image), the results will drop significantly when using our pretrained model. I feel sorry that I did not save the script of my preprocessing steps so cannot provide it to you now. We'd suggest you retrain the model using your own preprocessed data.

We have updated the results in our two recent work:
https://github.com/shiyujiao/cross_view_localization_SAFA.git
https://github.com/shiyujiao/cross_view_localization_DSM.git

You are welcome to follow our new works.

Thank you!

**Comment by wudongming97** [comment]
I will try it. Thanks a lot.
